version: '3.9'
name: minio

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=12345678
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    restart: always

volumes:
  minio-data:
