version: '3.9'
name: open-webui

services:

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "6969:8080"
    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui:
